### ISSUE TITLE
Error in processing.py file [apeer-ometiff-library]

### ISSUE THREAD

**Issue by abh799** [apeer-micro/apeer-ometiff-library#11]
I suspect some implementation error in processing.py file in two function definition, [ **apply_3d_trafo_zstack** ] and [ **apply_3d_trafo_rgb** ]

Brief: **array_out_5d** is first declared **none**, and is again used (without assigning any value) with indexing which results in error during execution of the function. 

![image](https://user-images.githubusercontent.com/35635880/72207226-f2c95c00-34bc-11ea-919b-ac6198b206e0.png)

**Comment by DaniGodin** [comment]
Hi,
Thx for the feedback, this is now fixed in the 1.7.0 update.
